{
  imports = [
    ./cmp.nix
    ./colorscheme.nix
    ./comments.nix
    ./direnv.nix
    ./git.nix
    ./icons.nix
    ./indent.nix
    ./keymaps.nix
    ./lastplace.nix
    ./lsp.nix
    ./mini.nix
    ./settings.nix
    ./snippets.nix
    ./telescope.nix
    ./todo.nix
    ./treesitter.nix
    ./trouble.nix
    ./undotree.nix
    ./which-key.nix
  ];
}
